version: 2
updates:
  - package-ecosystem: npm
    directory: /tally-web
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    groups:
      security:
        applies-to: security-updates
        patterns: ['*']
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    groups:
      security:
        applies-to: security-updates
        patterns: ['*']
