config:
  cloudflare:apiToken:
    secure: AAABAE+hQlRa20PFF1TQLe+3Ap0NLvMSkGpfBPc36IrRyMAiE7en5X5gKEXWRNjOHhs6QWt663c/WefOZJZ1Tvj9da1d98VU
  vercel:apiToken:
    secure: AAABALeY95TiHWHOve62FxdqgxVktNOP/oQ6lugdSF9EqkgGPIdpLoHGtcl8YeOh0P5hXnfACSs=
  tally-infra:clerkSecretKey:
    secure: AAABAITJePNFbOOIM28nIo/dNXkWWIpb8KZAUa2GZdzt0nR+Qkdp2XrAR3Hl4sT8Uhh18eT4vrRE0N13vpcC/j9mGeKZcDMNZX19edPXLIdT4g==
  tally-infra:clerkPublishableKey:
    secure: AAABADmercZcEOgJr0XJArm7+uMeb++PRc4BqIE16lRx9QEyc/nOGSB+1Tk6BK6uuGCfIZ27dlWa28E26FVfnC+TtC7AtPokHDxrTyR4HI+lH/YkSTYQxg==
  tally-infra:convexDeployment: dev:bright-jackal-396
  tally-infra:sentryAdminToken:
    secure: AAABAH7gcM8hJBUrGglAbNhJobin2EOli57cPvX2u7n/AypbeSEwYtMMx7v98qm3z/u9jdWsOIZwThb6UE8AYJ75M3xvU2xw1g6nq1JrLppffsaqVQzzV7G99HlNJo/nAuJdwKUYPA==
  launchdarkly:accessToken:
    secure: AAABAMdQT+IJ9bK0c1zFlhXIGMvwPbmD0RWHx4IyJSbJcwV0qS8v+pBTlC5k+PWZH5YVw1B0vx9qwjPRaEYmoL8dGCMLubio
