name: Tally
options:
  bundleIdPrefix: app.tally
  deploymentTarget:
    iOS: 17.0
packages:
  TallyCore:
    path: TallyCore
  Clerk:
    url: https://github.com/clerk/clerk-ios
    from: 0.57.0
targets:
  Tally:
    type: application
    platform: iOS
    sources:
      - path: TallyApp
    dependencies:
      - package: TallyCore
      - package: Clerk
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.tally.ios
        DEVELOPMENT_TEAM: ""
        GENERATE_INFOPLIST_FILE: YES
        CLERK_PUBLISHABLE_KEY: ""
        INFOPLIST_KEY_CLERK_PUBLISHABLE_KEY: "$(CLERK_PUBLISHABLE_KEY)"
  TallyTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: TallyAppTests
    dependencies:
      - target: Tally
  TallyUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: TallyAppUITests
        optional: true
    dependencies:
      - target: Tally
